[[Libcap_Ng]]
arch = "armv7l"
git-tree-sha1 = "411204d48eabe6384a7ae7c94407476604b48a4a"
libc = "glibc"
os = "linux"

    [[Libcap_Ng.download]]
    sha256 = "d6a14299d6b3081724c15813842a28a0d0be3948692bc80e1e12a841738467a7"
    url = "https://github.com/JuliaBinaryWrappers/Libcap_Ng_jll.jl/releases/download/Libcap_Ng-v0.7.10+1/Libcap_Ng.v0.7.10.armv7l-linux-gnueabihf.tar.gz"
[[Libcap_Ng]]
arch = "i686"
git-tree-sha1 = "3f6c4c88ce6e38fdd2b421f42ae695a6fb800578"
libc = "musl"
os = "linux"

    [[Libcap_Ng.download]]
    sha256 = "67017bf423c2dc928b99ad79ff9bdfcc84dc060cc7eca13e353d7efe3fb33ea7"
    url = "https://github.com/JuliaBinaryWrappers/Libcap_Ng_jll.jl/releases/download/Libcap_Ng-v0.7.10+1/Libcap_Ng.v0.7.10.i686-linux-musl.tar.gz"
[[Libcap_Ng]]
arch = "aarch64"
git-tree-sha1 = "99432d943a621f34d8d843f112826c836d38c2f7"
libc = "glibc"
os = "linux"

    [[Libcap_Ng.download]]
    sha256 = "857543bc4ee3df67202143c9f3d492d58bf2ebb30f477f82aa38fc4627f2baca"
    url = "https://github.com/JuliaBinaryWrappers/Libcap_Ng_jll.jl/releases/download/Libcap_Ng-v0.7.10+1/Libcap_Ng.v0.7.10.aarch64-linux-gnu.tar.gz"
[[Libcap_Ng]]
arch = "armv7l"
git-tree-sha1 = "d8050d9d4b81cc1f40e00bb067829fedf96c8d74"
libc = "musl"
os = "linux"

    [[Libcap_Ng.download]]
    sha256 = "1d1be40eaeac07de6c36e6e190088874555ec88fbf873a84d3c909d5fe9dc881"
    url = "https://github.com/JuliaBinaryWrappers/Libcap_Ng_jll.jl/releases/download/Libcap_Ng-v0.7.10+1/Libcap_Ng.v0.7.10.armv7l-linux-musleabihf.tar.gz"
[[Libcap_Ng]]
arch = "aarch64"
git-tree-sha1 = "92f05e5c253b33d1f4cdb357c8d135f45096c5b3"
libc = "musl"
os = "linux"

    [[Libcap_Ng.download]]
    sha256 = "e0f6ff15648200d38c282eca18aa732a4959436935f04839249707c38ab0836e"
    url = "https://github.com/JuliaBinaryWrappers/Libcap_Ng_jll.jl/releases/download/Libcap_Ng-v0.7.10+1/Libcap_Ng.v0.7.10.aarch64-linux-musl.tar.gz"
[[Libcap_Ng]]
arch = "i686"
git-tree-sha1 = "07215e0063820484d037dad39e7e5e88265bebc8"
libc = "glibc"
os = "linux"

    [[Libcap_Ng.download]]
    sha256 = "484a74290ceff29980033f48add8f328a72b3a9e11d7846b5a171937084a5292"
    url = "https://github.com/JuliaBinaryWrappers/Libcap_Ng_jll.jl/releases/download/Libcap_Ng-v0.7.10+1/Libcap_Ng.v0.7.10.i686-linux-gnu.tar.gz"
[[Libcap_Ng]]
arch = "x86_64"
git-tree-sha1 = "69ea198ee3a90347d89548f3b09ee6363a2a0d0f"
libc = "musl"
os = "linux"

    [[Libcap_Ng.download]]
    sha256 = "9c8487447ae7a6d7822cc30f75a1637dbd1710669b3bdcb86a9de7a473456014"
    url = "https://github.com/JuliaBinaryWrappers/Libcap_Ng_jll.jl/releases/download/Libcap_Ng-v0.7.10+1/Libcap_Ng.v0.7.10.x86_64-linux-musl.tar.gz"
[[Libcap_Ng]]
arch = "x86_64"
git-tree-sha1 = "2fe23469271decadad436be3fde080544d15aa12"
libc = "glibc"
os = "linux"

    [[Libcap_Ng.download]]
    sha256 = "e41d8a7766436b6cb22c5ced7ff667a501f9512c6ab7cfd19759b714956621a4"
    url = "https://github.com/JuliaBinaryWrappers/Libcap_Ng_jll.jl/releases/download/Libcap_Ng-v0.7.10+1/Libcap_Ng.v0.7.10.x86_64-linux-gnu.tar.gz"
[[Libcap_Ng]]
arch = "powerpc64le"
git-tree-sha1 = "99b062ebbc9e01a4f2e940d752ff27a639a6967f"
libc = "glibc"
os = "linux"

    [[Libcap_Ng.download]]
    sha256 = "a7d72b9f1e7e5aa98f8f7b5277919ed764f2988178a28093b010bacdbcce49ad"
    url = "https://github.com/JuliaBinaryWrappers/Libcap_Ng_jll.jl/releases/download/Libcap_Ng-v0.7.10+1/Libcap_Ng.v0.7.10.powerpc64le-linux-gnu.tar.gz"
